"""
DraftPredictor - loads the trained model and runs inference.

Two modes:
  1. Model loaded (.pkl exists): runs real XGBoost inference.
  2. No model (Phase 0-2, model not yet trained): returns None scores so Express
     falls back to statsService scores gracefully.
"""
import os
import json
import numpy as np
from pathlib import Path
from typing import Optional

try:
    import joblib
    JOBLIB_AVAILABLE = True
except ImportError:
    JOBLIB_AVAILABLE = False

from .schemas import PredictRequest, PredictResponse


#Champion list - must match the order used during feature engineering.
#Update this when new champions are released.
CHAMPIONS_JSON_PATH = Path(__file__).parent.parent / "data" / "champions.json"


def load_champion_list() -> list[str]:
    """Load the ordered champion list from disk (generated by seedChampions / Data Dragon)."""
    if CHAMPIONS_JSON_PATH.exists():
        with open(CHAMPIONS_JSON_PATH, "r") as f:
            return json.load(f)
    #Fallback: empty list (encoding will return zeros → model will give ~50% score)
    return []


class DraftPredictor:
    """
    Encapsulates model loading and feature engineering for draft prediction.

    Feature vector layout (mirrors extract_features.py):
      [enemy_picks_onehot × 5 roles]  165 × 5 = 825
      [ally_picks_onehot  × 4 roles]  165 × 4 = 660  (excludes player's own role)
      [bans_onehot]                   165
      [my_role_onehot]                5
      [candidate_onehot]              165
      [patch_normalized]              1
      ─────────────────────────────────
      Total: 1,821 features
    """

    ROLES = ["top", "jungle", "mid", "bot", "support"]

    def __init__(self, model_path: str):
        self.model_path = model_path
        self.model = None
        self.champion_list: list[str] = load_champion_list()
        self.n_champions = max(len(self.champion_list), 165)  #reserve space
        self.patch: Optional[str] = None
        self.model_name: Optional[str] = None
        self.metadata: dict = {}

        self._load()

    def _load(self) -> None:
        """Attempt to load model from disk. Silent failure if not trained yet."""
        path = Path(self.model_path)
        if not path.exists():
            print(f"[DraftPredictor] No model at {self.model_path} - running in stub mode.")
            return

        if not JOBLIB_AVAILABLE:
            print("[DraftPredictor] joblib not installed - cannot load model.")
            return

        try:
            data = joblib.load(path)
            #Support both raw model and dict with metadata
            if isinstance(data, dict):
                self.model = data.get("model")
                self.patch = data.get("patch")
                self.model_name = data.get("model_name", path.stem)
                self.metadata = data.get("metadata", {})
                if "champion_list" in data:
                    self.champion_list = data["champion_list"]
                    self.n_champions = len(self.champion_list)
            else:
                self.model = data
                self.model_name = path.stem

            print(f"[DraftPredictor] Loaded model: {self.model_name} (patch {self.patch})")
        except Exception as e:
            print(f"[DraftPredictor] Failed to load model: {e}")
            self.model = None

    def is_ready(self) -> bool:
        return self.model is not None

    def _champion_index(self, name: Optional[str]) -> Optional[int]:
        if not name:
            return None
        name_lower = name.lower()
        for i, c in enumerate(self.champion_list):
            if c.lower() == name_lower:
                return i
        return None

    def _encode_champion(self, name: Optional[str]) -> np.ndarray:
        """One-hot encode a single champion into a vector of size n_champions."""
        vec = np.zeros(self.n_champions, dtype=np.float32)
        idx = self._champion_index(name)
        if idx is not None:
            vec[idx] = 1.0
        return vec

    def build_features(self, req: PredictRequest) -> np.ndarray:
        """
        Converts a PredictRequest into the full feature vector.
        Must match the layout used in extract_features.py exactly.
        """
        n = self.n_champions

        #Enemy picks - one-hot per role (825 features for 165 champs × 5 roles)
        enemy_vec = np.concatenate([
            self._encode_champion(getattr(req.enemy_picks, role))
            for role in self.ROLES
        ])

        #Ally picks - one-hot per role, excluding player's own role (660 features)
        ally_roles = [r for r in self.ROLES if r != req.my_role]
        ally_vec = np.concatenate([
            self._encode_champion(getattr(req.ally_picks, role))
            for role in ally_roles
        ])

        #Bans - multi-hot (165 features)
        bans_vec = np.zeros(n, dtype=np.float32)
        for ban in req.bans:
            idx = self._champion_index(ban)
            if idx is not None:
                bans_vec[idx] = 1.0

        #My role - one-hot (5 features)
        role_vec = np.zeros(len(self.ROLES), dtype=np.float32)
        if req.my_role in self.ROLES:
            role_vec[self.ROLES.index(req.my_role)] = 1.0

        #Candidate champion - one-hot (165 features)
        candidate_vec = self._encode_champion(req.candidate_champion)

        #Patch - normalized float (1 feature, e.g. 14.8 → 0.148)
        patch_val = 0.0
        if self.patch:
            try:
                patch_val = float(self.patch) / 100.0
            except ValueError:
                pass
        patch_vec = np.array([patch_val], dtype=np.float32)

        return np.concatenate([
            enemy_vec, ally_vec, bans_vec, role_vec, candidate_vec, patch_vec
        ]).reshape(1, -1)

    def predict(self, req: PredictRequest) -> PredictResponse:
        """
        Returns a PredictResponse.
        If no model is loaded, returns null scores (Express falls back to statsService).
        """
        if not self.is_ready():
            return PredictResponse(
                counter_score=None,
                synergy_score=None,
                overall_score=None,
                patch=self.patch,
            )

        try:
            features = self.build_features(req)
            #XGBoost returns probabilities [P(loss), P(win)]
            proba = self.model.predict_proba(features)[0]
            win_prob = float(proba[1])  #P(win)

            #We run two separate inference passes:
            #Pass 1 (counter): full draft context → counter_score
            #Pass 2 (synergy): ally-only context → synergy_score
            #For now, single-model approximation until separate models are trained.
            counter_score = round(win_prob, 4)
            synergy_score = round(win_prob, 4)
            overall_score = round((counter_score * 0.6) + (synergy_score * 0.4), 4)

            return PredictResponse(
                counter_score=counter_score,
                synergy_score=synergy_score,
                overall_score=overall_score,
                patch=self.patch,
            )
        except Exception as e:
            print(f"[DraftPredictor] Inference error: {e}")
            return PredictResponse(
                counter_score=None,
                synergy_score=None,
                overall_score=None,
                patch=self.patch,
            )
